# RennerC. Week 5 Homework

### What does Pandas stand for?
##### Panel Data or Python Data Analysis
### What are the 2 collections used in Pandas?
##### Series and Data Frame
### Name 4 things Pandas can do for us.
##### Data Cleaning, Data Normalization, Data Visualization, and Data Inspection
### To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
##### inplace=True
### What is a CSV?
##### Comma-separated-value - organized data in rows and columns like a table
### When cleaning data what values do we not like in our data?
##### Nulls, duplicates, and incorrect data, 

In [2]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np
shapedArray = np.arange(12).reshape((2,3,2))
print(shapedArray)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
six = np.linspace(0, 20, num=6)
print(six)

[ 0.  4.  8. 12. 16. 20.]


In [5]:
# 9. Make a Deep Copy of the above array
import copy
copy6 = copy.deepcopy(six)
print(copy6)

[ 0.  4.  8. 12. 16. 20.]


In [7]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
#    ```python
#             ([[25, 16]])
#             ([[11, 2], [13, 4]])
#             ([[7, 81], [5, 6], [11, 12]])
#     ```

a1= ([[25, 16]])
a2 = ([[11, 2], [13, 4]])
a3 = ([[7, 81], [5, 6], [11, 12]])

newarray = np.concatenate((a1, a2, a3), axis = 0)
print(newarray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [8]:
# 11. Sort 'newArray' in order into 'sortedArray'
sortedarray = np.sort(newarray)
print(sortedarray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [19]:
# 12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
reshapedArray = sortedarray.reshape(4,3,)
v1, v2, v3, v4 = reshapedArray
print(v1)
print(v2)
print(v3)
print(v4)


[16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]


In [7]:
# 13. Combined and sort the following arrays into one called 'comboArray' ...
#         one = ([10, 11, 12, 13, 14, 15, 16, 17])
#         two = ([20, 21, 22, 23, 24, 25, 26, 27])
#         three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.concatenate((one, two, three))
comboArray = np.sort(comboArray)
print(comboArray)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [12]:
# 14. Take 'comboArray' and perform the following slicing activities:
#     - print sec1 - the 2nd element
print(comboArray[1])
#     - print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
#     - print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:14])
#     - print sec4 - the last 6 elements
print(comboArray[-6:])
#     - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-10])
#     - print sec6 - from #20 every even element to the end
print(comboArray[16::2])
#     - print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1::-5])



1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [3]:
# 15. Using `Series`, create a `DataFrame` that looks like this:

#     | Ingredients | Quantity | Unit |
#     |----|----|----|
#     | Flour | 4 | cups |
#     | Milk | 1 | cup |
#     | Eggs | 2 | large |
#     | Spam | 1 | can |

#     Name: Dinner, dtype: object
import pandas as pd
Ingredients = pd.Series(["Flour","Milk","Eggs", "Spam"], name= 'Ingredients')
Quantity = pd.Series([4,1,2,1],name= 'Quantity')
Unit  = pd.Series(["cups","cup", "large", "can"],name= 'Unit')
df = pd.concat([Ingredients, Quantity, Unit], axis = 1)
df.name = "Dinner"
df


Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [10]:

# 16. Take this data and create a DataFrame named studentData
#         {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#             'Height': [5.1, 6.2, 5.1, 5.2],
#             'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#             'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#             'Age': [21, 23, 24, 21],
#             'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#             'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']

students = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}
studentData = pd.DataFrame(students)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [11]:
# 17. Add a new column to the DataFrame with the following deserts:
#         ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['deserts'] = deserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [12]:
# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ['Name', 'address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [39]:
# 19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

#     ```python
#         df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#     ```
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
print(df)
df.to_csv("cows_and_goats.csv")

        Cows  Goats
Year 1    12     22
Year 2    20     19


In [11]:
# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
veg = pd.DataFrame({'Vegetables':['brocolli', 'carrot','potato'], 'Color':['green', 'orange', 'brown']})
print(veg)
veg.to_csv("Vegetables.csv", index = False)

import pandas as pd
df = pd.read_csv("Vegetables.csv")
add = pd.DataFrame({'quantity (lbs)': [1.7,2.8,3.9]})
df = pd.concat([df, add], axis=1)
print(df)
df.to_csv("Vegetable(lbs).csv", index = False)


  Vegetables   Color
0   brocolli   green
1     carrot  orange
2     potato   brown
  Vegetables   Color  quantity (lbs)
0   brocolli   green             1.7
1     carrot  orange             2.8
2     potato   brown             3.9
